#!/usr/bin/env python3
"""
Build README.md (English) and README.zh-CN.md (Chinese) from:
  - data/stars.json      (full GitHub starred metadata)
  - data/categories.json (category tree, bilingual labels)
  - data/manifest.json   (per-repo: category, subcategory, zh description)

Re-run this script after editing manifest.json or categories.json.
"""
from __future__ import annotations
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
STARS = json.loads((ROOT / "data" / "stars.json").read_text())
CATS = json.loads((ROOT / "data" / "categories.json").read_text())["categories"]
MANIFEST = json.loads((ROOT / "data" / "manifest.json").read_text())

STARS_BY_NAME = {r["full_name"]: r for r in STARS}


def fmt_stars(n: int) -> str:
    if n >= 1000:
        return f"{n/1000:.1f}k".replace(".0k", "k")
    return str(n)


def slug(text: str) -> str:
    """Match GitHub's github-slugger algorithm: lowercase, space→dash, then strip
    invalid chars (emoji, punctuation) WITHOUT collapsing dashes."""
    s = text.strip().lower()
    s = s.replace(" ", "-")
    # Keep: word chars (incl. unicode letters/digits/_), hyphens, CJK ranges.
    # Strip: emoji, punctuation like & / etc.
    s = re.sub(r"[^\w一-鿿㐀-䶿-]", "", s)
    return s


def topics_cell(topics: list[str], max_n: int = 4) -> str:
    if not topics:
        return ""
    chosen = topics[:max_n]
    return " ".join(f"`{t}`" for t in chosen)


def archived_marker(repo: dict) -> str:
    return " ⚠️" if repo.get("archived") else ""


def repo_link(name: str) -> str:
    return f"[{name}](https://github.com/{name})"


def description_for(name: str, lang: str) -> str:
    repo = STARS_BY_NAME[name]
    desc = (repo.get("description") or "").strip()
    if lang == "en":
        return desc or "—"
    # Chinese
    return MANIFEST[name].get("zh") or desc or "—"


def build_table(rows: list[str], lang: str) -> str:
    if lang == "en":
        header = "| Repo | Description | Lang | ⭐ | Topics |\n|---|---|---|---|---|"
    else:
        header = "| 仓库 | 描述 | 语言 | ⭐ | 标签 |\n|---|---|---|---|---|"
    return "\n".join([header] + rows)


def assignments_index() -> dict:
    """Return {cat_id: {sub_id_or_None: [full_name, ...]}}, sorted by stars desc."""
    idx: dict = {}
    for name, m in MANIFEST.items():
        cat = m["category"]
        sub = m.get("subcategory")
        idx.setdefault(cat, {}).setdefault(sub, []).append(name)
    # sort each list by stars desc
    for cat in idx.values():
        for sub_list in cat.values():
            sub_list.sort(
                key=lambda n: STARS_BY_NAME[n].get("stargazers_count", 0),
                reverse=True,
            )
    return idx


def build_readme(lang: str) -> str:
    assert lang in ("en", "zh")
    idx = assignments_index()
    out: list[str] = []

    # Header
    if lang == "en":
        out.append("# Solo Unicorn Toolbox 🛠️\n")
        out.append("> A personal aggregator of GitHub tools, tutorials, and resources I have collected from GitHub stars, Twitter bookmarks, Xiaohongshu and other sources.\n")
        out.append("> 中文版本：[README.zh-CN.md](./README.zh-CN.md)\n")
        out.append(f"**Total: {len(MANIFEST)} repositories** · Auto-generated by `scripts/build-readme.py`. To add new entries, paste GitHub URLs into [`inbox.md`](./inbox.md).\n")
        out.append("---\n")
        out.append("## Table of Contents\n")
    else:
        out.append("# Solo Unicorn Toolbox 🛠️\n")
        out.append("> 个人 GitHub 工具/教程/资源聚合库，收集自 GitHub Stars、Twitter Bookmarks、小红书收藏等。\n")
        out.append("> English version: [README.md](./README.md)\n")
        out.append(f"**共 {len(MANIFEST)} 个项目** · 由 `scripts/build-readme.py` 自动生成。要添加新条目，把 GitHub URL 粘到 [`inbox.md`](./inbox.md)。\n")
        out.append("---\n")
        out.append("## 目录\n")

    # TOC
    for cat in CATS:
        cat_count = sum(len(v) for v in idx.get(cat["id"], {}).values())
        if cat_count == 0:
            continue
        label = cat["en"] if lang == "en" else cat["zh"]
        anchor = slug(f"{cat['emoji']} {label}")
        out.append(f"- [{cat['emoji']} {label} ({cat_count})](#{anchor})")
    out.append("")

    out.append("---\n")

    # Sections
    for cat in CATS:
        sub_index = idx.get(cat["id"], {})
        cat_count = sum(len(v) for v in sub_index.values())
        if cat_count == 0:
            continue
        label = cat["en"] if lang == "en" else cat["zh"]
        out.append(f"## {cat['emoji']} {label}\n")

        # If subcategories defined, render each as ###
        sub_defs = cat.get("subcategories") or []
        sub_id_to_def = {s["id"]: s for s in sub_defs}

        # Order: defined subcats first, then None ("uncategorized in section")
        ordered_sub_ids = [s["id"] for s in sub_defs if s["id"] in sub_index]
        if None in sub_index:
            ordered_sub_ids.append(None)

        for sub_id in ordered_sub_ids:
            names = sub_index[sub_id]
            if not names:
                continue
            if sub_id is not None:
                sdef = sub_id_to_def[sub_id]
                slabel = sdef["en"] if lang == "en" else sdef["zh"]
                out.append(f"### {slabel} ({len(names)})\n")
            elif sub_defs:
                # Uncategorized within a section that has subcats
                slabel = "Other" if lang == "en" else "其他"
                out.append(f"### {slabel} ({len(names)})\n")
            # Build rows
            rows = []
            for name in names:
                repo = STARS_BY_NAME[name]
                lang_field = repo.get("language") or "—"
                star = fmt_stars(repo.get("stargazers_count", 0))
                topics = topics_cell(repo.get("topics") or [])
                desc = description_for(name, lang)
                # Escape pipes inside description
                desc = desc.replace("|", "\\|")
                marker = archived_marker(repo)
                rows.append(
                    f"| {repo_link(name)}{marker} | {desc} | {lang_field} | {star} | {topics} |"
                )
            out.append(build_table(rows, lang))
            out.append("")

        out.append("")

    # Footer
    out.append("---\n")
    if lang == "en":
        out.append("**Legend**: ⚠️ = repo is archived. Stars are point-in-time. Topic tags are from GitHub.\n")
        out.append("**Maintenance**: Run `scripts/sync-stars.sh` to pull new stars into `inbox.md`. Edit `data/manifest.json` to (re)classify or rewrite descriptions, then run `python3 scripts/build-readme.py`.\n")
    else:
        out.append("**图例**：⚠️ = 项目已被原作者 archive。Star 数为某时点快照。Topic 标签来自 GitHub。\n")
        out.append("**维护**：跑 `scripts/sync-stars.sh` 把新增 star 拉进 `inbox.md`；编辑 `data/manifest.json` 调整分类或重写描述，再跑 `python3 scripts/build-readme.py`。\n")

    return "\n".join(out)


def main() -> None:
    en = build_readme("en")
    zh = build_readme("zh")
    (ROOT / "README.md").write_text(en)
    (ROOT / "README.zh-CN.md").write_text(zh)
    print(f"Wrote README.md ({len(en):,} chars)")
    print(f"Wrote README.zh-CN.md ({len(zh):,} chars)")
    # Coverage stats per category
    idx = assignments_index()
    print("\nCoverage:")
    for cat in CATS:
        total = sum(len(v) for v in idx.get(cat["id"], {}).values())
        print(f"  {cat['emoji']} {cat['en']:48s} {total:>4d}")
    print(f"  {'TOTAL':>50s}  {len(MANIFEST):>4d}")


if __name__ == "__main__":
    main()
